# Generated by engine --emit-module gcp/google_storage_bucket
# @engine.v1 audit-bundle: terraform/gcp/google_storage_bucket@9f38ef5a70db92ec443ce18432d7fa5242b53b37.tar.gz
# Upstream:    checkov@3.2.524
# Upstream:    kics@v2.1.20
# Upstream:    regula@master
# Provider:    hashicorp/google
#
# Controls applied to this resource:
#   ckv-gcp-114  public_access_prevention = "enforced"
#   ckv-gcp-29   uniform_bucket_level_access = true
#   ckv-gcp-63   logging.log_bucket = var.logging_log_bucket
#   ckv-gcp-78   versioning.enabled = true
#
# Controls enforced via Sentinel policy (run emit-policy to write):
#   ckv2-gcp-4  Ensure that retention policies on log buckets are configured using Bucket Lock
#   regula-fg-r00420  Storage buckets should not be anonymously or publicly accessible
#   ckv2-gcp-9  Ensure that Container Registry repositories are not anonymously or publicly accessible
#
# Controls not emitted (BaseResourceCheck — no attribute path):
#   ckv-gcp-62  Bucket should log access
#   ckv-gcp-28  Ensure that Cloud Storage bucket is not anonymously or publicly accessible
#
# Coupled-resource module emitted (D117 / D172 / D174 Phase 2):
#   parent renders as ``resource "<type>" "this"``;  N attached as "main".
#   regula-fg-r00420  google_storage_bucket + google_storage_bucket_iam_member
#
resource "google_storage_bucket" "this" {
  # value=var (provider schema requires this attribute; no rule gates a value)
  location = var.location

  # value=var (provider schema requires this attribute; no rule gates a value)
  name = var.name

  # @engine.v1 attr=public_access_prevention ctrl=ckv-gcp-114 role=primary upstream=checkov src=literal expected="enforced"
  # ckv-gcp-114: Ensure public access prevention is enforced on Cloud Storage bucket
  public_access_prevention = "enforced"

  # @engine.v1 attr=uniform_bucket_level_access ctrl=ckv-gcp-29 role=primary upstream=checkov src=literal expected=true
  # @engine.v1 attr=uniform_bucket_level_access ctrl=kics-bb0db090-5509-4853-a827-75ced0b3caa0 role=concurring upstream=kics src=literal expected=true
  # ckv-gcp-29 (checkov): Ensure that Cloud Storage buckets have uniform bucket-level access enabled
  # kics-bb0db090-5509-4853-a827-75ced0b3caa0 [concurring] (kics): Google Storage Bucket Level Access Disabled
  uniform_bucket_level_access = false

  # value=var (operational: no rule constraint; operator supplies)
  default_event_based_hold = var.default_event_based_hold

  # value=var (operational: no rule constraint; operator supplies)
  enable_object_retention = var.enable_object_retention

  # value=var (operational: no rule constraint; operator supplies)
  force_destroy = var.force_destroy

  # value=var (operational: no rule constraint; operator supplies)
  labels = var.labels

  # value=var (operational: no rule constraint; operator supplies)
  requester_pays = var.requester_pays

  # value=var (operational: no rule constraint; operator supplies)
  storage_class = var.storage_class

  # ckv-gcp-63: Bucket should not log to itself
  logging {
    log_bucket = var.logging_log_bucket
  }

  # ckv-gcp-78: Ensure Cloud storage has versioning enabled
  versioning {
    enabled = true
  }
}

resource "google_storage_bucket_iam_member" "main" {
  bucket = google_storage_bucket.this.name

  # value=var (provider schema requires this attribute; no rule gates a value)
  member = var.member

  # value=var (provider schema requires this attribute; no rule gates a value)
  role = var.role
}
